language: java
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java11-installer
cache:
  directories:
  - $HOME/.m2/
before_script:
  - mvn -v
script:  mvn package
jdk: oraclejdk11
env: TERM=dumb
